// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="@nuxtjs/pwa" />
/// <reference types="@nuxtjs/gtm" />
/// <reference types="@nuxtjs/google-analytics" />
/// <reference types="nuxt-purgecss" />
/// <reference types="@nuxtjs/stylelint-module" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxtjs/style-resources" />
/// <reference types="nuxt-svg-loader" />
/// <reference types="@nuxtjs/sitemap" />
/// <reference types="vue-scrollto" />
/// <reference types="@nuxt/components" />
/// <reference path=".nuxt/nitro.d.ts" />
/// <reference types="unplugin-vue2-script-setup/types" />
/// <reference path=".nuxt/auto-imports.d.ts" />
export {};
